# Generated by Django 3.2.12 on 2022-02-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220130_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zippcode',
            new_name='zipcode',
        ),
    ]
